version: '3'

services:
  db:
    image: mdillon/postgis
    ports:
    - "5432:5432"
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 20M
    volumes:
       - './es/:/usr/share/elasticsearch/data'
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - .:/code/static_src/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch5
